export const CREATE_EMPLOYEE_REQUEST = "CREATE_EMPLOYEE_REQUEST";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const CREATE_EMPLOYEE_FAIL = "CREATE_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const GET_EMPLOYEE_BYID_REQUEST = "GET_EMPLOYEE_BYID_REQUEST";
export const GET_EMPLOYEE_BYID_SUCCESS = "GET_EMPLOYEE_BYID_SUCCESS";
export const GET_EMPLOYEE_BYID_FAIL = "GET_EMPLOYEE_BYID_FAIL";

export const LIST_EMPLOYEE_REQUEST = "LIST_EMPLOYEE_REQUEST";
export const LIST_EMPLOYEE_SUCCESS = "UPDATE_SUCCESS";
export const LIST_EMPLOYEE_FAIL = "LIST_EMPLOYEE_FAIL";


export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_EMPLOYEE_FAIL = "DELETE_FAIL";
